# Generated by Django 4.2.30 on 2026-10-07 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='show_in_menu',
            field=models.BooleanField(default=True, help_text='Untick to hide this category from the menu bar. Its products still appear under All items.'),
        ),
    ]
